In [60]:
import scipy.io as sio
import numpy as np
import pickle
data=sio.loadmat('tcgabrca_molecular_data_shuffled.mat')
sio.whosmat('tcgabrca_molecular_data_shuffled.mat')

[('labelshuffled', (1, 380), 'double'),
 ('methylshuffled', (574, 380), 'double'),
 ('mirnashuffled', (1046, 380), 'double'),
 ('patientidshuffled', (380,), 'char'),
 ('rnashuffled', (17814, 380), 'double'),
 ('rppashuffled', (171, 380), 'double')]

In [61]:
labelshuffled = data['labelshuffled']
methylshuffled = data['methylshuffled']
mirnashuffled = data['mirnashuffled']
patientidshuffled = data['patientidshuffled']
rnashuffled = data['rnashuffled']
rppashuffled = data['rppashuffled']

In [62]:
label_train = labelshuffled[:,0:300]
label_test = labelshuffled[:,300:380]
methyl_train = methylshuffled[:,0:300]
methyl_test = methylshuffled[:,300:380]

In [63]:
def accuracy(A,data,label):
    pred = np.dot(np.linalg.pinv(A),data)
    pred=np.dot(B,pred).T
    row_sums = pred.sum(axis=1)
    pred = pred / row_sums[:, np.newaxis]
    print(pred)
    pred=np.argmax(pred, axis=1)
    print(pred)
    accuracy=np.equal(pred,label).sum()/label.shape[1]
    return accuracy

In [64]:
def ssnmf(X,y,lamda = 0.75, r = 35,n_itr = 1000, k=4):
    m, n = X.shape
    y = y.reshape(-1)
    print(m,n)
    S = np.random.rand(r, n)
    A = np.random.rand(m, r)
    B = np.random.rand(k, r)
    Y = np.eye(k)[y].T
    eps = np.spacing(1)
    try:
        with open('variable.pkl', 'rb') as f:
            A = pickle.load(f)
            B = pickle.load(f)
            S = pickle.load(f)
            f.close()
    except Exception:
        S = np.random.rand(r, n)
        A = np.random.rand(m, r)
        B = np.random.rand(k, r)
        
    for i in range(n_itr):
        A *= (np.dot( X, S.T)) / (np.dot(np.dot( A, S), S.T) + eps)
        B *= (np.dot( Y, S.T)) / (np.dot(np.dot( B, S), S.T) + eps)
        S *= (np.dot( A.T, X)+ lamda * np.dot( B.T, Y)) / (np.dot( A.T, np.dot( A, S)+ eps)+ lamda * np.dot( B.T, np.dot( B, S)+ eps))
        print("iteration", i, euclid_divergence(X, Y, A, B, S, lamda ))
    
    with open('variable.pkl', 'wb') as f:
        pickle.dump(A, f)
        pickle.dump(B, f)
        pickle.dump(S, f)
        f.close()
    return S, A, B    
        

def euclid_divergence( X, Y, A, B, S, lamda):
    d = ((X - np.dot(A, S))**2).sum() + lamda * ((Y - np.dot(B, S))**2).sum() 
    return d        

In [179]:
S, A, B = ssnmf(methyl_train,label_train)

574 300
iteration 0 2513.7968422
iteration 1 2513.79578965
iteration 2 2513.79472845
iteration 3 2513.79365826
iteration 4 2513.79257875
iteration 5 2513.79148962
iteration 6 2513.79039057
iteration 7 2513.78928134
iteration 8 2513.78816172
iteration 9 2513.78703151
iteration 10 2513.78589054
iteration 11 2513.78473873
iteration 12 2513.78357598
iteration 13 2513.78240229
iteration 14 2513.78121768
iteration 15 2513.78002224
iteration 16 2513.77881609
iteration 17 2513.77759942
iteration 18 2513.77637247
iteration 19 2513.77513553
iteration 20 2513.77388895
iteration 21 2513.77263313
iteration 22 2513.77136851
iteration 23 2513.7700956
iteration 24 2513.76881494
iteration 25 2513.76752713
iteration 26 2513.7662328
iteration 27 2513.76493264
iteration 28 2513.76362733
iteration 29 2513.76231764
iteration 30 2513.76100431
iteration 31 2513.75968815
iteration 32 2513.75836995
iteration 33 2513.75705052
iteration 34 2513.75573069
iteration 35 2513.75441129
iteration 36 2513.75309313
iterat

iteration 302 2513.52110516
iteration 303 2513.52036874
iteration 304 2513.51963306
iteration 305 2513.51889812
iteration 306 2513.51816389
iteration 307 2513.51743037
iteration 308 2513.51669754
iteration 309 2513.5159654
iteration 310 2513.51523394
iteration 311 2513.51450314
iteration 312 2513.513773
iteration 313 2513.51304352
iteration 314 2513.51231468
iteration 315 2513.51158649
iteration 316 2513.51085895
iteration 317 2513.51013205
iteration 318 2513.50940579
iteration 319 2513.50868017
iteration 320 2513.50795519
iteration 321 2513.50723085
iteration 322 2513.50650715
iteration 323 2513.50578409
iteration 324 2513.50506166
iteration 325 2513.50433986
iteration 326 2513.50361869
iteration 327 2513.50289814
iteration 328 2513.5021782
iteration 329 2513.50145885
iteration 330 2513.50074007
iteration 331 2513.50002186
iteration 332 2513.49930417
iteration 333 2513.498587
iteration 334 2513.49787029
iteration 335 2513.49715403
iteration 336 2513.49643817
iteration 337 2513.4957226

iteration 598 2513.27403392
iteration 599 2513.273334
iteration 600 2513.27263661
iteration 601 2513.27194163
iteration 602 2513.27124897
iteration 603 2513.27055852
iteration 604 2513.26987018
iteration 605 2513.26918382
iteration 606 2513.26849935
iteration 607 2513.26781665
iteration 608 2513.26713561
iteration 609 2513.26645614
iteration 610 2513.26577812
iteration 611 2513.26510146
iteration 612 2513.26442604
iteration 613 2513.26375178
iteration 614 2513.26307857
iteration 615 2513.26240631
iteration 616 2513.26173492
iteration 617 2513.26106431
iteration 618 2513.26039439
iteration 619 2513.25972508
iteration 620 2513.25905629
iteration 621 2513.25838795
iteration 622 2513.25771998
iteration 623 2513.25705231
iteration 624 2513.25638488
iteration 625 2513.25571762
iteration 626 2513.25505046
iteration 627 2513.25438335
iteration 628 2513.25371623
iteration 629 2513.25304904
iteration 630 2513.25238174
iteration 631 2513.25171429
iteration 632 2513.25104662
iteration 633 2513.250

iteration 895 2513.05484019
iteration 896 2513.05418243
iteration 897 2513.05352523
iteration 898 2513.05286849
iteration 899 2513.0522121
iteration 900 2513.05155597
iteration 901 2513.05089998
iteration 902 2513.05024403
iteration 903 2513.04958801
iteration 904 2513.04893182
iteration 905 2513.04827534
iteration 906 2513.04761847
iteration 907 2513.04696109
iteration 908 2513.04630309
iteration 909 2513.04564436
iteration 910 2513.04498479
iteration 911 2513.04432427
iteration 912 2513.04366269
iteration 913 2513.04299994
iteration 914 2513.04233593
iteration 915 2513.04167053
iteration 916 2513.04100365
iteration 917 2513.04033518
iteration 918 2513.03966504
iteration 919 2513.03899313
iteration 920 2513.03831936
iteration 921 2513.03764363
iteration 922 2513.03696588
iteration 923 2513.03628602
iteration 924 2513.03560399
iteration 925 2513.03491972
iteration 926 2513.03423316
iteration 927 2513.03354424
iteration 928 2513.03285294
iteration 929 2513.03215921
iteration 930 2513.03

In [180]:
print('test' , accuracy(A,methyl_test,label_test))
print('train' , accuracy(A,methyl_train,label_train))

test 0.675
train 0.9


In [65]:
def ssnmfnew(X,y,lamda = 0.75, r = 35,n_itr = 1000, k=4):
    m, n = X.shape
    y = y[:,0:300]
    y = y.reshape(-1)
    L = np.ones([k,300])
    L_test = np.zeros([k,80])
    L = np.concatenate((L,L_test),axis=1)
    y_test = np.zeros([k,80])
    print(m,n)
    S = np.random.rand(r, n)
    A = np.random.rand(m, r)
    B = np.random.rand(k, r)
    Y = np.eye(k)[y].T
    Y = np.concatenate((Y,y_test),axis=1)
    eps = np.spacing(1)
    try:
        with open('variable_methyl.pkl', 'rb') as f:
            A = pickle.load(f)
            B = pickle.load(f)
            S = pickle.load(f)
            f.close()
    except Exception:
        S = np.random.rand(r, n)
        A = np.random.rand(m, r)
        B = np.random.rand(k, r)
        
    for i in range(n_itr):
        A *= (np.dot( X, S.T)) / (np.dot(np.dot( A, S), S.T) + eps)
        B *= (np.dot(L * Y, S.T)) / (np.dot(L * np.dot( B, S), S.T) + eps)
        S *= (np.dot( A.T, X)+ lamda * np.dot( B.T,L * Y)) / (np.dot( A.T, np.dot( A, S)+ eps)+ lamda * np.dot( B.T,L * np.dot( B, S)+ eps))
        print("iteration", i, euclid_divergence(X, Y, A, B, S, lamda ))
    
    with open('variable_methyl.pkl', 'wb') as f:
        pickle.dump(A, f)
        pickle.dump(B, f)
        pickle.dump(S, f)
        f.close()
    return S, A, B    

In [79]:
pred = np.dot(B,S)
pred = np.argmax(pred, axis=0)
accuracy=np.equal(pred,labelshuffled).sum()/labelshuffled.shape[1]
print(accuracy)
print(labelshuffled)
print(pred)

0.915789473684
[[2 2 3 2 3 2 1 3 1 3 0 0 2 2 0 3 2 3 3 3 3 2 2 3 3 3 3 0 2 3 2 2 1 1 2 3 2
  2 3 2 2 3 0 0 1 2 0 0 0 1 3 2 2 2 2 3 3 1 2 1 2 0 2 2 2 2 2 1 2 3 0 3 2 0
  2 2 2 2 2 2 3 1 2 1 2 2 0 0 2 2 2 3 3 2 1 2 2 1 0 2 2 2 0 0 2 2 2 2 0 2 2
  0 0 0 3 2 0 0 1 0 2 3 3 2 3 3 3 0 2 3 2 2 2 2 0 2 2 2 3 3 3 2 2 0 3 3 1 3
  2 2 1 0 1 3 2 2 2 2 2 3 0 2 0 3 1 1 2 2 3 1 1 3 0 0 2 0 2 2 1 0 0 2 1 2 3
  2 2 1 1 3 1 2 3 2 2 2 2 2 2 0 0 2 2 3 2 1 1 1 2 1 2 1 2 3 3 2 2 0 0 3 0 3
  3 2 3 2 3 2 2 3 2 0 0 2 0 0 2 2 0 1 3 3 2 2 0 1 0 2 3 0 3 1 3 3 2 2 0 3 2
  3 0 1 2 2 2 2 0 0 2 0 2 2 2 2 2 3 2 3 0 0 3 1 2 0 1 0 0 2 2 1 3 3 1 3 3 3
  1 2 2 3 0 3 0 0 2 2 2 2 2 3 2 2 0 3 1 2 0 3 0 0 1 2 3 3 0 2 3 3 3 2 2 0 2
  2 3 3 3 2 2 3 2 0 2 2 2 2 2 2 3 3 0 2 1 2 2 3 2 0 3 3 1 2 3 1 2 0 0 3 2 0
  0 2 1 0 3 2 2 2 2 0]]
[2 2 3 2 3 2 1 3 1 3 0 0 2 2 0 3 2 3 3 3 3 2 2 3 3 3 3 0 2 3 2 2 1 1 2 3 2
 2 3 2 2 3 0 0 1 2 0 0 0 1 3 2 2 2 2 3 3 1 2 1 2 0 2 2 2 2 2 1 2 3 0 3 2 0
 2 2 2 2 2 2 3 1 2 1 2 2 0 0 2 2 2 3 3 2 1 2 2 1 0 

In [94]:
l = labelshuffled[:, 300:380]
b = pred[300:380]
np.equal(l,b).sum()

49

In [66]:
#rppashuffled1=rppashuffled+10
S, A ,B = ssnmfnew(methylshuffled,labelshuffled,lamda = 0.75, r = 35,n_itr = 1000, k=4)
ac = accuracy(A, methylshuffled, labelshuffled)
print('test' , ac)

574 380
iteration 0 6875.14780708
iteration 1 6829.16547004
iteration 2 6806.73289769
iteration 3 6783.91509676
iteration 4 6759.99925439
iteration 5 6734.1970791
iteration 6 6705.56493649
iteration 7 6672.95858702
iteration 8 6635.00034727
iteration 9 6590.07720322
iteration 10 6536.40204735
iteration 11 6472.18365778
iteration 12 6395.95197922
iteration 13 6307.04768813
iteration 14 6206.18075718
iteration 15 6095.81060387
iteration 16 5980.02510651
iteration 17 5863.76588491
iteration 18 5751.64607042
iteration 19 5646.92083782
iteration 20 5551.07711339
iteration 21 5464.08292908
iteration 22 5384.98350844
iteration 23 5312.49133822
iteration 24 5245.38268194
iteration 25 5182.68039
iteration 26 5123.68484142
iteration 27 5067.92643095
iteration 28 5015.09383716
iteration 29 4964.96849095
iteration 30 4917.37741532
iteration 31 4872.16557388
iteration 32 4829.18361606
iteration 33 4788.2854263
iteration 34 4749.33045237
iteration 35 4712.18720989
iteration 36 4676.73591143
iteratio

iteration 304 3492.27685523
iteration 305 3491.83407362
iteration 306 3491.39459958
iteration 307 3490.95841578
iteration 308 3490.52550307
iteration 309 3490.09584021
iteration 310 3489.66940368
iteration 311 3489.24616778
iteration 312 3488.82610479
iteration 313 3488.4091853
iteration 314 3487.99537853
iteration 315 3487.58465277
iteration 316 3487.17697576
iteration 317 3486.77231499
iteration 318 3486.3706381
iteration 319 3485.97191303
iteration 320 3485.57610827
iteration 321 3485.18319294
iteration 322 3484.79313687
iteration 323 3484.40591064
iteration 324 3484.02148556
iteration 325 3483.63983363
iteration 326 3483.26092749
iteration 327 3482.88474035
iteration 328 3482.51124593
iteration 329 3482.14041838
iteration 330 3481.7722322
iteration 331 3481.4066622
iteration 332 3481.04368338
iteration 333 3480.68327097
iteration 334 3480.32540027
iteration 335 3479.97004669
iteration 336 3479.61718569
iteration 337 3479.26679274
iteration 338 3478.91884331
iteration 339 3478.57331

iteration 618 3426.54523037
iteration 619 3426.44360139
iteration 620 3426.34228946
iteration 621 3426.24129635
iteration 622 3426.14062457
iteration 623 3426.04027712
iteration 624 3425.94025737
iteration 625 3425.84056875
iteration 626 3425.74121449
iteration 627 3425.64219738
iteration 628 3425.54351954
iteration 629 3425.4451822
iteration 630 3425.34718561
iteration 631 3425.24952893
iteration 632 3425.15221032
iteration 633 3425.05522693
iteration 634 3424.95857506
iteration 635 3424.8622503
iteration 636 3424.76624772
iteration 637 3424.67056201
iteration 638 3424.57518764
iteration 639 3424.48011902
iteration 640 3424.38535059
iteration 641 3424.29087691
iteration 642 3424.19669273
iteration 643 3424.10279298
iteration 644 3424.00917287
iteration 645 3423.9158278
iteration 646 3423.82275343
iteration 647 3423.72994561
iteration 648 3423.6374004
iteration 649 3423.54511401
iteration 650 3423.45308285
iteration 651 3423.36130342
iteration 652 3423.26977239
iteration 653 3423.17848

iteration 922 3404.93617038
iteration 923 3404.88677445
iteration 924 3404.83751215
iteration 925 3404.78838224
iteration 926 3404.73938341
iteration 927 3404.69051425
iteration 928 3404.64177325
iteration 929 3404.59315884
iteration 930 3404.5446694
iteration 931 3404.49630322
iteration 932 3404.44805856
iteration 933 3404.39993365
iteration 934 3404.35192667
iteration 935 3404.30403578
iteration 936 3404.25625912
iteration 937 3404.20859484
iteration 938 3404.16104104
iteration 939 3404.11359587
iteration 940 3404.06625746
iteration 941 3404.01902393
iteration 942 3403.97189345
iteration 943 3403.92486417
iteration 944 3403.87793429
iteration 945 3403.83110198
iteration 946 3403.78436548
iteration 947 3403.737723
iteration 948 3403.69117278
iteration 949 3403.64471309
iteration 950 3403.5983422
iteration 951 3403.55205837
iteration 952 3403.50585988
iteration 953 3403.45974503
iteration 954 3403.41371207
iteration 955 3403.3677593
iteration 956 3403.32188495
iteration 957 3403.276087

In [14]:
rppashuffled1=rppashuffled+10
S, A ,B = ssnmfnew(rppashuffled1,labelshuffled,lamda = 0.75, r = 35,n_itr = 100, k=4)
accuracy(A,rppashuffled1,labelshuffled)
print('test' , accuracy(A,rppashuffled1,labelshuffled))
# np.isnan(rppashuffled)
#print('train' , accuracy(A,methyl_train,label_train))

171 380
iteration 0 2830.25096684
iteration 1 2830.25079935
iteration 2 2830.25063186
iteration 3 2830.25046438
iteration 4 2830.25029691
iteration 5 2830.25012946
iteration 6 2830.24996201
iteration 7 2830.24979457
iteration 8 2830.24962715
iteration 9 2830.24945973
iteration 10 2830.24929232
iteration 11 2830.24912493
iteration 12 2830.24895754
iteration 13 2830.24879017
iteration 14 2830.2486228
iteration 15 2830.24845544
iteration 16 2830.2482881
iteration 17 2830.24812076
iteration 18 2830.24795343
iteration 19 2830.24778612
iteration 20 2830.24761881
iteration 21 2830.24745152
iteration 22 2830.24728423
iteration 23 2830.24711696
iteration 24 2830.24694969
iteration 25 2830.24678243
iteration 26 2830.24661519
iteration 27 2830.24644795
iteration 28 2830.24628073
iteration 29 2830.24611351
iteration 30 2830.24594631
iteration 31 2830.24577911
iteration 32 2830.24561192
iteration 33 2830.24544475
iteration 34 2830.24527758
iteration 35 2830.24511043
iteration 36 2830.24494328
itera

In [15]:
import pandas as pd

In [52]:
def storeresult(A,data,label):
    pred = np.dot(np.linalg.pinv(A),data)
    pred=np.dot(B,pred).T
    row_sums = pred.sum(axis=1)
    pred = pred / row_sums[:, np.newaxis]
    #print(pred)
    print(pred.shape)
    print(label.shape)
    df = pd.DataFrame(pred)
    pred=np.argmax(pred, axis=1)
    df['pred'] = np.array(pred)
    df['label'] = label.T
    df.to_csv('methyl_pred.csv')
    #print(pred)
    accuracy=np.equal(pred,label).sum()/label.shape[1]
    return accuracy    


In [53]:
storeresult(A,methylshuffled,labelshuffled)

(380, 4)
(1, 380)


0.77105263157894732

In [31]:
storeresult(A,rppashuffled1,labelshuffled)

(380, 4)
(1, 380)


0.76315789473684215

In [41]:
pred = np.dot(B,S)
pred = pred.T
row_sums = pred.sum(axis=1)
pred = pred / row_sums[:, np.newaxis]
print(pred)
pred=np.argmax(pred, axis=1)
print(pred)
label = labelshuffled
df = pd.DataFrame(pred)
pred=np.argmax(pred, axis=0)
df['pred'] = np.array(pred)
df['label'] = label.T
df.to_csv('rppa_pred_BS.csv')
accuracy=np.equal(pred,label).sum()/label.shape[1]
print(accuracy)

[[  1.76222509e-01   2.64479193e-02   5.23374290e-01   2.73955282e-01]
 [  7.11705380e-02   9.85365658e-11   5.47325556e-01   3.81503906e-01]
 [  2.92848388e-01   9.07530014e-02   1.52977672e-01   4.63420939e-01]
 ..., 
 [  2.50140724e-10   1.83810721e-01   4.87604104e-01   3.28585175e-01]
 [  3.45943886e-02   7.28661928e-02   7.35383917e-01   1.57155501e-01]
 [  9.48708629e-02   1.14758433e-01   6.18744917e-01   1.71625787e-01]]
[2 2 3 2 3 2 2 3 1 3 0 0 2 2 0 3 2 3 3 2 3 2 2 3 2 3 3 0 2 2 2 2 2 1 3 2 2
 2 3 2 2 2 2 0 1 0 0 0 0 1 2 2 2 2 2 3 3 2 2 1 2 0 2 2 2 2 2 2 2 3 0 2 2 0
 2 2 2 2 2 2 2 0 2 0 3 2 0 0 2 2 3 3 3 2 1 2 2 1 0 2 2 2 0 2 2 2 2 2 0 1 2
 0 0 0 3 3 0 0 1 0 2 2 3 2 3 2 2 0 2 2 2 2 2 3 0 2 2 3 2 3 3 2 2 0 2 3 1 3
 2 2 1 0 1 3 3 2 2 2 2 3 0 2 0 3 1 3 2 2 3 2 0 3 0 0 2 0 2 2 1 0 1 2 0 2 3
 2 2 1 3 3 1 2 2 2 2 2 2 2 2 0 0 2 2 3 2 3 1 1 2 0 2 2 2 3 2 2 2 0 0 3 0 3
 2 2 3 2 1 2 3 2 3 0 0 2 0 0 2 2 0 3 2 3 2 2 0 2 0 2 3 0 3 1 1 1 2 2 0 3 2
 3 0 1 2 2 2 0 0 0 2 0 2 2 2 2 2 3 3 2 0 